apiVersion: v1
kind: Service
metadata:
  name: blastradius-backend
  labels:
    app: blastradius
    component: backend
spec:
  type: NodePort
  selector:
    app: blastradius
    component: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
